image: node:16.15

variables:
    HUGO_VERSION: '0.115.4'
    HUGO_CHECKSUM: 'f930fcc5559337233d24de3704a09b877a6cd29449241b69e111e10b24f6e200'
    HUGO_ENV: 'production'

stages:
    - build
    - deploy

before_script:
    - apt update && apt install --no-install-recommends  -yqq curl
      ca-certificates git
    - npm install -g npm
    - npm install -g postcss postcss-cli
    - curl -L -o hugo.tar.gz
      https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION\_Linux-64bit.tar.gz
    - echo "$HUGO_CHECKSUM  hugo.tar.gz" | sha256sum -c
    - tar xzvf hugo.tar.gz && cp ./hugo /usr/bin/hugo
    - hugo version

build:
    stage: build
    script:
        - npm install
        - hugo --minify -d public
    artifacts:
        paths:
            - public

pages:
    stage: deploy
    script: /bin/true
    only:
        - master
    artifacts:
        paths:
            - public
    dependencies:
        - build
