baseURL                    = "/"
canonifyURLs               = false
copyright                  = "© 2007-Today / Setyo. All rights reserved."
disableHugoGeneratorInject = true
enableEmoji                = true
enableRobotsTXT            = true
footnoteReturnLinkContents = "↩"
languageCode               = "id"
languageName               = "Indonesian"
MetaDataFormat             = "yaml"
title                      = "Setyo's Note"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = true
[menus]
  [[menus.main]]
    name    = 'About'
    pageRef = '/about'
  [[menus.main]]
    name    = 'Posts'
    pageRef = '/posts'
  [[menus.main]]
    name    = 'Projects'
    pageRef = '/projects'
  [[menus.main]]
    name    = 'Uses'
    pageRef = '/uses'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source       = 'hugo_stats.json'
    target       = 'assets/notwatching/hugo_stats.json'
[pagination]
  pagerSize = 5
